services:
  - type: web
    name: mission-freight-invoice-tool
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --host 0.0.0.0 --port $PORT app:app
    autoDeploy: false
